# Generated by Django 4.1.2 on 2022-12-05 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('description', models.TextField(verbose_name='Описание упражнения')),
                ('sport_type', models.CharField(blank=True, max_length=200, verbose_name='Вид спорта')),
                ('duration', models.TimeField(verbose_name='Длительность')),
                ('kkal_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Килокалории')),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дистанция')),
                ('avg_speed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Средняя скорость (м/с)')),
                ('max_speed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальная скорость (м/с)')),
                ('weigth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Поднимаемый вес')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('description', models.TextField(verbose_name='Описание тренировки')),
                ('begin_time', models.TimeField(blank=True, verbose_name='Начало тренировки')),
                ('kkal_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Килокалории')),
                ('tasks', models.ManyToManyField(to='training_site_api.trainingtask', verbose_name='Упражнения')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthdate', models.DateField(verbose_name='День рождения')),
                ('user_weigth', models.PositiveSmallIntegerField(default=70, verbose_name='Вес')),
                ('user_heigth', models.PositiveSmallIntegerField(default=175, verbose_name='Рост')),
                ('imt', models.FloatField(blank=True, verbose_name='Индекс массы тела')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка профиля')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Календарный день')),
                ('weeks_day', models.CharField(max_length=20, verbose_name='День недели')),
                ('max_temperature', models.SmallIntegerField(default=0, verbose_name='Максимальная температура дня')),
                ('min_temperature', models.PositiveSmallIntegerField(default=0, verbose_name='Влажность воздуха')),
                ('wind_speed', models.PositiveSmallIntegerField(default=0, verbose_name='Скорость ветра (м/с)')),
                ('kkal_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Килокалории за день')),
                ('trainings', models.ManyToManyField(to='training_site_api.training', verbose_name='Тренировки')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
    ]
