# Generated by Django 4.1.2 on 2022-12-09 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_site_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigth_step', models.PositiveSmallIntegerField(default=5, verbose_name='Шаг веса')),
                ('repeat_step', models.PositiveSmallIntegerField(default=2, verbose_name='Повторы')),
                ('cardio_duration_step', models.PositiveSmallIntegerField(default=60, verbose_name='Шаг длительности')),
                ('sets_pause', models.PositiveSmallIntegerField(default=90, verbose_name='Отдых между подходами')),
                ('repeat_pause', models.PositiveSmallIntegerField(default=150, verbose_name='Отдых между упражнениями')),
                ('rest_duration_step', models.PositiveSmallIntegerField(default=1, verbose_name='Шаг длительности')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['name'], 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.RemoveField(
            model_name='day',
            name='kkal_quantity',
        ),
        migrations.RemoveField(
            model_name='day',
            name='trainings',
        ),
        migrations.RemoveField(
            model_name='day',
            name='weeks_day',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='person',
            name='imt',
        ),
        migrations.RemoveField(
            model_name='training',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
        migrations.RemoveField(
            model_name='training',
            name='kkal_quantity',
        ),
        migrations.RemoveField(
            model_name='trainingtask',
            name='avg_speed',
        ),
        migrations.RemoveField(
            model_name='trainingtask',
            name='kkal_quantity',
        ),
        migrations.RemoveField(
            model_name='trainingtask',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='trainingtask',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trainingtask',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='training',
            name='training_date',
            field=models.ManyToManyField(blank=True, to='training_site_api.day', verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='musclegroup_type',
            field=models.CharField(choices=[('STRENGHT', 'Силовые'), ('CARDIO', 'Кардио')], default='BICEPS', max_length=8, verbose_name='Группа мышц'),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='reps_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Количество повторений'),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='task_type',
            field=models.CharField(choices=[('STRENGHT', 'Силовые'), ('CARDIO', 'Кардио')], default='STRENGHT', max_length=8, verbose_name='Тип упражнения'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='day',
            name='max_temperature',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Максимальная температура дня'),
        ),
        migrations.AlterField(
            model_name='day',
            name='min_temperature',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Влажность воздуха'),
        ),
        migrations.AlterField(
            model_name='day',
            name='wind_speed',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Скорость ветра (м/с)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='vorname',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='duration',
            field=models.TimeField(default='00:01:00', verbose_name='Длительность(мин.)'),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='weigth',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Поднимаемый вес'),
        ),
        migrations.CreateModel(
            name='UserMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Параметр измерений')),
                ('mesurement_date', models.DateField(auto_now=True, verbose_name='Дата измерения')),
                ('length', models.PositiveSmallIntegerField(default=0, verbose_name='Длина (см)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_site_api.person')),
            ],
            options={
                'verbose_name': 'Измерение параметра пользователя',
                'verbose_name_plural': 'Измерения параметров пользователя',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='user_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training_site_api.usersettings'),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='task_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='training_site_api.usersettings'),
        ),
    ]
