# Generated by Django 4.1.2 on 2022-12-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_site_api', '0002_usersettings_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_site_api.usersettings'),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='musclegroup_type',
            field=models.CharField(choices=[('BICEPS', 'Бицепс'), ('CHEST', 'Грудь'), ('LEGS', 'Ноги'), ('SHOULDERS', 'Плечи'), ('ABS', 'Пресс'), ('HANDS', 'Руки'), ('BACK', 'Спина'), ('TRICEPS', 'Трицепс'), ('NECK', 'Шея')], default='BICEPS', max_length=10, verbose_name='Группа мышц'),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='task_type',
            field=models.CharField(choices=[('STRENGHT', 'Силовые'), ('CARDIO', 'Кардио')], default='STRENGHT', max_length=9, verbose_name='Тип упражнения'),
        ),
        migrations.AlterField(
            model_name='usermeasurements',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training_site_api.person'),
        ),
    ]
