# Generated by Django 4.1.2 on 2022-12-09 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_site_api', '0003_alter_person_user_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройки шага измерений упражнения', 'verbose_name_plural': 'Настройки шагов измерений упражнений'},
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
